apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret-stg
  namespace: default
spec:
  secretName: tls-secret-stg
  dnsNames:
    - ___SiteDnsName___
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - ___SiteDnsName___
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
