apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: eplast2
  name: routing-for-eplast
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: eplast2.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: eplastapi
          servicePort: 5000
